name: docker-build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
env:
  CR_PATH: ghcr.io/anlab-kaist

jobs:
  image:
    strategy:
      matrix:
        image:
          ["git-jekyll", "jenkins", "actions-runner", "dnsmasq", "iptables", "dnscrypt-proxy"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image image
        run: |
          docker build ${{ matrix.image }} --tag ${{matrix.image}}:latest

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.CR_NAME }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          docker tag ${{matrix.image}}:latest $CR_PATH/${{matrix.image}}:latest
          docker push $CR_PATH/${{matrix.image}}:latest
      - uses: gautamkrishnar/keepalive-workflow@v1
